#!/bin/bash

echo Starting Switches...
echo

python3 switch.py 0 localhost 3000 &
python3 switch.py 1 localhost 3000 &
python3 switch.py 2 localhost 3000 &
python3 switch.py 3 localhost 3000 &
python3 switch.py 4 localhost 3000 &
# python3 switch.py 5 localhost 3000 &

echo
echo Done Starting Switches...
echo Press Enter to Kill all Switches and Controller
read
pkill python3

